get:
  tags:
    - Credentials
  summary: Exibe credencial
  description: |
    Pesquisa uma credencial pelo ID e exibe os dados.
  parameters:
    - name: id
      in: path
      equired: true
      description: Id da credencial
      schema:
        type: integer
        format: int64
        example: 1
  responses:
    "200":
      description: "Success"
      content:
        application/json:
          schema:
            $ref: "../schemas/credentials-response.yaml"
    "400":
      $ref: "../schemas/common-errors.yaml#/components/responses/ValidationIdParamError"
    "401":
      $ref: "../schemas/common-errors.yaml#/components/responses/UnauthorizedError"
    "404":
      $ref: "../schemas/common-errors.yaml#/components/responses/NotFoundError"
    "500":
      $ref: "../schemas/common-errors.yaml#/components/responses/UnknownError"

delete:
  tags:
    - Credentials
  summary: Deleta uma credencial
  description: |
    Deleta uma credencial cadastrada.
  parameters:
    - name: id
      in: path
      equired: true
      description: Id da credencial
      schema:
        type: integer
        format: int64
        example: 1
  responses:
    "204":
      description: "Success"
    "400":
      $ref: "../schemas/common-errors.yaml#/components/responses/ValidationIdParamError"
    "401":
      $ref: "../schemas/common-errors.yaml#/components/responses/UnauthorizedError"
    "404":
      $ref: "../schemas/common-errors.yaml#/components/responses/NotFoundError"
    "500":
      $ref: "../schemas/common-errors.yaml#/components/responses/UnknownError"