post:
  tags:
    - Credentials
  summary: Cria nova credencial
  description: |
    Endpoint responsável pela criação de novas credenciais de acessos para utilização de serviços de terceiros.
  requestBody:
    required: true
    content:
      application/json:
        schema:
          $ref: "../schemas/credentials-request.yaml"
  responses:
    "201":
      description: "Success"
      content:
        application/json:
          schema:
            $ref: "../schemas/credentials-response.yaml"
    "400":
      $ref: "../schemas/common-errors.yaml#/components/responses/ValidationError"
    "401":
      $ref: "../schemas/common-errors.yaml#/components/responses/UnauthorizedError"
    "409":
      $ref: "../schemas/common-errors.yaml#/components/responses/AlreadyExistsError"
      examples:
          validationError:
            summary: Already Exists
            value:
              success: false
              error: ALREADY_EXISTS_ERROR
              message: "Already exists a credential with the received name."
    "500":
      $ref: "../schemas/common-errors.yaml#/components/responses/UnknownError"

get:
  tags:
    - Credentials
  summary: Pesquisa credenciais existentes
  description: |
    Lista todas as credenciais cadastradas permitindo também a aplicação de filtros de pesquisa.
  parameters:
    - $ref: "../schemas/search-params.yaml#/components/parameters/PageParam"
    - $ref: "../schemas/search-params.yaml#/components/parameters/LimitParam"
    - $ref: "../schemas/search-params.yaml#/components/parameters/SearchParam"
    - $ref: "../schemas/search-params.yaml#/components/parameters/FilterParam"
  responses:
    "200":
      description: "Success"
      content:
        application/json:
          schema:
            $ref: "../schemas/credentials-request.yaml"
    "400":
      $ref: "../schemas/common-errors.yaml#/components/responses/ValidationError"
    "401":
      $ref: "../schemas/common-errors.yaml#/components/responses/UnauthorizedError"
    "500":
      description: Unknown
      content:
        application/json:
          schema:
            allOf:
              - $ref: "../schemas/error-base-response.yaml"
              - type: object
                properties:
                  message:
                    type: string
                    example: "Internal Server Error"