get:
  tags:
    - Permission
  summary: Exibe permissão
  description: >
    Localiza e exibe permissão pelo id fornecido.
  parameters:
    - name: id
      in: path
      required: true
      description: Id da permissão pesquisada.
      schema:
        type: integer
        example: 1
  responses:
    "200":
      description: "Permissão localizada"
      content:
        application/json:
          schema:
            allOf:
              - $ref: "../schemas/success-base-response.yaml"
              - type: object
                properties:
                  resources:
                    $ref: "../schemas/permission.yaml"
    "400":
      description: "Requisição errada"
      content:
        application/json:
          schema:
            $ref: "../schemas/error-base-response.yaml"
          examples:
            validationError:
              summary: Dados inválidos
              value:
                success: false
                error: "VALIDATION_ERROR"
                message: "id: Invalid input: expected number, received NaN"
    "401":
      $ref: "../schemas/error-unauthorized.yaml"

    "404":
      description: "Não encontrado"
      content:
        application/json:
          schema:
            $ref: "../schemas/error-base-response.yaml"
          examples:
            notFound:
              summary: Não encontrado
              value:
                success: false
                error: "NOT_FOUND_ERROR"
                message: "Not found permission with received id."
    "500":
      description: Erro interno no servidor
      content:
        application/json:
          schema:
            $ref: "../schemas/error-base-response.yaml"

delete:
  tags:
    - Permission
  summary: Deleta uma permissão
  description: >
    Localiza e deleta uma permissão pelo id fornecido.
  parameters:
    - name: id
      in: path
      required: true
      description: Id da permissão pesquisada.
      schema:
        type: integer
        example: 1
  responses:
    "204":
      description: "Permissão excluída"
      
    "400":
      description: "Requisição errada"
      content:
        application/json:
          schema:
            $ref: "../schemas/error-base-response.yaml"
          examples:
            validationError:
              summary: Dados inválidos
              value:
                success: false
                error: "VALIDATION_ERROR"
                message: "id: Invalid input: expected number, received NaN"
    "401":
      $ref: "../schemas/error-unauthorized.yaml"

    "404":
      description: "Não encontrado"
      content:
        application/json:
          schema:
            $ref: "../schemas/error-base-response.yaml"
          examples:
            notFound:
              summary: Não encontrado
              value:
                success: false
                error: "NOT_FOUND_ERROR"
                message: "Not found permission with received id."
    "500":
      description: Erro interno no servidor
      content:
        application/json:
          schema:
            $ref: "../schemas/error-base-response.yaml"

patch:
  tags:
    - Permission
  summary: Atualiza uma permissão
  description: >
    Localiza uma permissão pelo Id e depois atualiza seus dados.<br>
    Por diretriz os campos resource e method utilizam caixa alta, 
    então quaquer envio em caixa baixa será automáticamente transofrmado.
  parameters:
    - name: id
      in: path
      required: true
      description: Id da permissão pesquisada.
      schema:
        type: integer
        example: 1
  requestBody:
    content:
      application/json:
        schema:
          allOf:
            - $ref: "../schemas/permission-update.yaml"
  responses:
    "200":
      description: "Permissão atualizada"
      content:
        application/json:
          schema:
            allOf:
              - $ref: "../schemas/success-base-response.yaml"
              - type: object
                properties:
                  resources:
                    $ref: "../schemas/permission.yaml"
      
    "400":
      description: "Requisição errada"
      content:
        application/json:
          schema:
            $ref: "../schemas/error-base-response.yaml"
          examples:
            validationError:
              summary: Dados inválidos
              value:
                success: false
                error: "VALIDATION_ERROR"
                message: "resource: Too big: expected string to have <=25 characters"
    "401":
      $ref: "../schemas/error-unauthorized.yaml"

    "404":
      description: "Não encontrado"
      content:
        application/json:
          schema:
            $ref: "../schemas/error-base-response.yaml"
          examples:
            notFound:
              summary: Não encontrado
              value:
                success: false
                error: "NOT_FOUND_ERROR"
                message: "Permission not found with received id."
    "500":
      description: Erro interno no servidor
      content:
        application/json:
          schema:
            $ref: "../schemas/error-base-response.yaml"  