get:
  tags:
    - Profile
  summary: Exibe perfil do usuário
  description: |
    Exibe os dados do perfil do usuário logado no momento.
  responses:
    "200":
      description: "Success"
      content:
        applicatoin/json:
          schema: 
            allOf:
              - $ref: "../schemas/success-base-response.yaml#"
              - type: object
                properties:
                  resources:
                    $ref: "../schemas/user-profile.yaml"
    "401":
      $ref: "../schemas/common-errors.yaml#/components/responses/UnauthorizedError"
    "500":
      $ref: "../schemas/common-errors.yaml#/components/responses/UnknownError"