FROM node:lts-slim as development

WORKDIR /app

COPY . .

ENV NODE_ENV=development
ENV JWT_PRIVATE_KEY_PASSPHRASE=parangaricutirimicuaro
ENV JWT_REFRESH_KEY_PASSPHRASE=passphrase
ENV JWT_PRIVATE_KEY_PATH=certs/private.key.pem
ENV JWT_PUBLIC_KEY_PATH=certs/public.key.pem

RUN npm install


CMD ["npm", "run", "dev"]


# faz a build
FROM node:lts-slim as builder

WORKDIR /app

COPY package*.json ./
COPY tsconfig.json ./

RUN npm install

COPY . .

RUN npm run build

#faz o deploy
FROM node:lts-slim as production

WORKDIR /app

COPY --from=builder /app/package*.json ./
COPY --from=builder /app/dist ./dist
COPY --from=builder /app/start.sh ./

RUN npm install --omit=dev

ENV NODE_ENV=production
ENV JWT_PRIVATE_KEY_PATH=certs/private.key.pem
ENV JWT_PUBLIC_KEY_PATH=certs/public.key.pem


EXPOSE 3000

CMD ["sh", "./start.sh"]