components:
  responses:
    SessionExpiredError:
      description: "Unauthorized"
      content:
        application/json:
          schema:
            allOf: 
              - $ref: "./error-base-response.yaml#"
          examples:
            sessionExpiredError:
              summary: "Session Expired"
              value:
                success: false
                error: "SESSION_EXPIRED_ERROR"
                message: "The received credentials is expired, re-create u`r session."
    UnknownError:
      description: "Unknown"
      content:
        application/json:
          schema:
            allOf: 
              - $ref: "./error-base-response.yaml#"
          examples:
            sessionExpiredError:
              summary: "Unknown"
              value:
                success: false
                error: "UNKNOWN_ERROR"
                message: "Internal Server Error."
