type: object

required:
  - name
  
properties:
  name:
    type: string
    example: "ERP Credentials"
  
  accessToken:
    type: string
    example: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c"
  
  refreshToken:
    type: string
    example: "ghp_aBcDeFgHiJkLmNoPqRsTuVwXyZ0123456789"
  code:
    type: string
    example: "54948944549849649C"
  
  accountId:
    type: string
    example: "12"
  
