type: object
allOf:
  - $ref: "./success-base-response.yaml"
  - type: object
    properties:
      resources:
        allOf:
          - $ref: "./base-entity.yaml"
          - $ref: "./credentials-request.yaml"