type: object
required:
  - id
  - name
  - email
  
properties:
  name:
    type: string
    example: John Doe
    minLength: 3
    maxLength: 50

  email:
    type: string
    example: john@doe.com
  
  password:
    type: string
    minLength: 8
    maxLength: 16
    pattern: '^(?=.*\d)(?=.*[A-Z])(?=.*[a-z])(?=.*[^\w\d\s:])([^\s]){8,16}'
    example: '@MeuPassword1'